### ISSUE TITLE
p10bmc: phosphor-image-updater: terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'

### ISSUE THREAD

**Issue by lxwinspur** [openbmc/phosphor-bmc-code-mgmt#12]
In the rainier machine, after the BMC is booted frequently, the `phosphor-image-updater` process fails to start due to the following reasons:

```
p10bmc phosphor-image-updater[571]: terminate called after throwing an instance of `std::filesystem::__cxx11::filesystem_error`
p10bmc phosphor-image-updater[571]: what(): filesystem error: status: Bad message [/media/rofs-a/etc/os-release]
```

**Comment by anoo1** [comment]
The item_updater.cpp file is using `fs::is_regular_file(osRelease)` to determine if the os-release file exists, and if it's not present it'd attempt to delete that bad backup image. But this check is throwing an exception because of a corrupted filesystem, therefore it should be changed the non-throwing form of `is_regular_file(path, error_code)` since the objective is to determine if the os-release exists or not, not to throw an error.

**Comment by lxwinspur** [comment]
@anoo1 
review by: https://gerrit.openbmc.org/c/openbmc/phosphor-bmc-code-mgmt/+/60716
